#!/usr/bin/env python3
"""Build LaTeX macros for reviewer-requested revision analyses."""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

BATCHES = {
    "MATR-05-12": "May",
    "MATR-06-30": "June",
    "MATR-04-12": "April",
}


def cmd(name: str, value: object) -> str:
    return rf"\renewcommand{{\{name}}}{{{value}}}"


def fmt(value: object, digits: int = 3) -> str:
    return f"{float(value):.{digits}f}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    root = args.root.resolve()
    output = (args.output or root / "revision_results.tex").resolve()

    lines = [
        "% Generated by code/build_revision_macros.py. Do not edit.",
        r"\newcommand{\RevisionMetricsReady}{0}",
        r"\newcommand{\NestedAuditReady}{0}",
    ]
    for prefix in BATCHES.values():
        for stem in [
            "MoveMCSE", "MoveMCSECycles", "MeanAbsNaive", "MeanAbsCross",
            "AbsImprove", "AbsImproveMCSE", "RelativeErrorReduction",
            "EndpointBoundWidth", "NestedSigned", "GlobalSigned", "NestedAbs",
            "GlobalAbs", "NestedMinusGlobalSigned", "NestedMinusGlobalSignedMCSE",
            "NestedMinusGlobalAbs", "NestedMinusGlobalAbsMCSE", "NestedPtenESS",
            "NestedPninetyFiveW", "NestedMaxUnitShare", "NestedCalibrationBrier",
            "NestedCalibrationObserved", "NestedCalibrationPredicted",
            "NestedEventPfiveMinESS", "NestedEventPninetyFiveMaxW",
            "NestedEventOverallMaxW", "NestedEventMaxIncrement",
            "NestedOverlaysWgtHundred",
        ]:
            lines.append(rf"\newcommand{{\Matr{prefix}{stem}}}{{--}}")

    metrics_path = root / "results" / "revision_metrics" / "revision_accuracy_summary.csv"
    if metrics_path.exists():
        d = pd.read_csv(metrics_path)
        lines.append(cmd("RevisionMetricsReady", 1))
        for batch, prefix in BATCHES.items():
            row = d[d["scope"] == batch]
            if len(row) != 1:
                raise RuntimeError(f"Expected one revision metric row for {batch}")
            r = row.iloc[0]
            lines.extend([
                cmd(f"Matr{prefix}MoveMCSE", fmt(r["mcse_crossfit_minus_naive_movement_pp"])),
                cmd(f"Matr{prefix}MoveMCSECycles", fmt(abs(r["mcse_crossfit_minus_naive_movement_cycles"]), 2)),
                cmd(f"Matr{prefix}MeanAbsNaive", fmt(r["mean_naive_absolute_error_pct"])),
                cmd(f"Matr{prefix}MeanAbsCross", fmt(r["mean_crossfit_absolute_error_pct"])),
                cmd(f"Matr{prefix}AbsImprove", fmt(r["mean_absolute_error_improvement_pp"])),
                cmd(f"Matr{prefix}AbsImproveMCSE", fmt(r["mcse_absolute_error_improvement_pp"])),
                cmd(f"Matr{prefix}RelativeErrorReduction", fmt(100.0 * r["relative_absolute_error_reduction"], 1)),
                cmd(f"Matr{prefix}EndpointBoundWidth", fmt(r["endpoint_identification_bound_width_cycles"], 2)),
            ])

    nested_dir = root / "results" / "matr_nested_preprocessing"
    est_path = nested_dir / "estimator_summary.csv"
    paired_path = nested_dir / "paired_summary.csv"
    weight_path = nested_dir / "weight_diagnostics.csv"
    dominance_path = nested_dir / "unit_dominance.csv"
    calibration_path = nested_dir / "heldout_calibration.csv"
    event_path = nested_dir / "event_time_diagnostics.csv"
    fit_path = nested_dir / "fold_preprocessing_and_fit.csv"
    if all(path.exists() for path in [est_path, paired_path, weight_path, dominance_path, calibration_path, event_path, fit_path]):
        est = pd.read_csv(est_path)
        paired = pd.read_csv(paired_path)
        weights = pd.read_csv(weight_path)
        dominance = pd.read_csv(dominance_path)
        calibration = pd.read_csv(calibration_path)
        events = pd.read_csv(event_path)
        fits = pd.read_csv(fit_path)
        if len(fits) == 0:
            raise RuntimeError("Nested fit output is empty")
        lines.append(cmd("NestedAuditReady", 1))
        lines.append(r"\newcommand{\NestedTotalFits}{%d}" % len(fits))
        lines.append(r"\newcommand{\NestedFallbackFits}{%d}" % int(fits["solver_method"].astype(str).str.startswith("fallback_").sum()))
        for batch, prefix in BATCHES.items():
            def erow(arm: str):
                x = est[(est["scope"] == batch) & (est["arm"] == arm)]
                if len(x) != 1:
                    raise RuntimeError(f"Expected one estimator row: {batch}/{arm}")
                return x.iloc[0]
            global_row = erow("global_preprocessing_crossfit")
            nested_row = erow("nested_preprocessing_crossfit")

            def prow(metric: str):
                x = paired[(paired["scope"] == batch) & (paired["metric"] == metric)]
                if len(x) != 1:
                    raise RuntimeError(f"Expected one paired row: {batch}/{metric}")
                return x.iloc[0]
            signed = prow("nested_minus_global_signed_error_pp")
            absolute = prow("nested_minus_global_absolute_error_pp")

            ww = weights[
                (weights["scope"] == batch)
                & (weights["arm"] == "nested_preprocessing_crossfit")
                & np.isclose(weights["checkpoint_fraction_H"].astype(float), 1.0)
            ]
            dd = dominance[
                (dominance["batch"] == batch)
                & (dominance["arm"] == "nested_preprocessing_crossfit")
            ]
            cc = calibration[calibration["batch"] == batch]
            ee = events[
                (events["scope"] == batch)
                & (events["arm"] == "nested_preprocessing_crossfit")
            ]
            per_overlay = ee.groupby("replicate", as_index=False).agg(
                min_ess_over_risk=("ess_over_n_at_risk", "min"),
                max_weight=("max_weight", "max"),
                max_hazard_increment=("weighted_hazard_increment", "max"),
            )
            overall_max_weight = float(per_overlay["max_weight"].max())
            if overall_max_weight >= 1000:
                overall_max_weight_tex = rf"{overall_max_weight / 1e5:.2f}\\times10^{{5}}"
            else:
                overall_max_weight_tex = fmt(overall_max_weight, 2)
            lines.extend([
                cmd(f"Matr{prefix}GlobalSigned", fmt(global_row["mean_signed_gap_pct"])),
                cmd(f"Matr{prefix}NestedSigned", fmt(nested_row["mean_signed_gap_pct"])),
                cmd(f"Matr{prefix}GlobalAbs", fmt(global_row["mean_absolute_gap_pct"])),
                cmd(f"Matr{prefix}NestedAbs", fmt(nested_row["mean_absolute_gap_pct"])),
                cmd(f"Matr{prefix}NestedMinusGlobalSigned", fmt(signed["mean"])),
                cmd(f"Matr{prefix}NestedMinusGlobalSignedMCSE", fmt(signed["mcse"])),
                cmd(f"Matr{prefix}NestedMinusGlobalAbs", fmt(absolute["mean"])),
                cmd(f"Matr{prefix}NestedMinusGlobalAbsMCSE", fmt(absolute["mcse"])),
                cmd(f"Matr{prefix}NestedPtenESS", fmt(np.percentile(ww["ess_over_n_at_risk"], 10))),
                cmd(f"Matr{prefix}NestedPninetyFiveW", fmt(np.percentile(ww["max_weight"], 95), 2)),
                cmd(f"Matr{prefix}NestedMaxUnitShare", fmt(dd["largest_unit_risk_weight_share"].max(), 3)),
                cmd(f"Matr{prefix}NestedCalibrationBrier", fmt(np.average(cc["brier_score"], weights=cc["n_rows"]), 5)),
                cmd(f"Matr{prefix}NestedCalibrationObserved", fmt(np.average(cc["observed_censor_rate"], weights=cc["n_rows"]), 5)),
                cmd(f"Matr{prefix}NestedCalibrationPredicted", fmt(np.average(cc["mean_predicted_censor_probability"], weights=cc["n_rows"]), 5)),
                cmd(f"Matr{prefix}NestedEventPfiveMinESS", fmt(np.percentile(per_overlay["min_ess_over_risk"], 5))),
                cmd(f"Matr{prefix}NestedEventPninetyFiveMaxW", fmt(np.percentile(per_overlay["max_weight"], 95), 2)),
                cmd(f"Matr{prefix}NestedEventOverallMaxW", overall_max_weight_tex),
                cmd(f"Matr{prefix}NestedEventMaxIncrement", fmt(per_overlay["max_hazard_increment"].max())),
                cmd(f"Matr{prefix}NestedOverlaysWgtHundred", f"{int((per_overlay['max_weight'] > 100).sum())}/{len(per_overlay)}"),
            ])

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
