#!/usr/bin/env python3
"""Build reviewer-requested accuracy and paired-Monte-Carlo summaries.

The script reads the overlay-level output from ``matr_primary_analysis.py`` and
reports final error, absolute-error improvement, relative error reduction, and
the Monte Carlo standard error of each paired contrast.  Estimator movement is
retained as a descriptive quantity rather than used as a recovery criterion.
"""
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

BATCHES = {
    "MATR-05-12": ("May", "loader rule", 81.51),
    "MATR-06-30": ("June", "observed 0.88-Ah crossing", 0.0),
    "MATR-04-12": ("April", "loader rule", 72.95),
}


def _mcse(values: Iterable[float]) -> float:
    x = np.asarray(list(values), float)
    x = x[np.isfinite(x)]
    if len(x) <= 1:
        return 0.0 if len(x) == 1 else float("nan")
    return float(np.std(x, ddof=1) / math.sqrt(len(x)))


def _fmt(x: float, digits: int = 3) -> str:
    return f"{float(x):.{digits}f}"


def _write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError(f"No rows to write: {path}")
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument(
        "--replicates",
        type=Path,
        default=None,
        help="Defaults to ROOT/results/matr_primary/replicates.csv",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Defaults to ROOT/results/revision_metrics",
    )
    parser.add_argument(
        "--tolerance-pct",
        type=float,
        default=None,
        help=(
            "Optional externally justified engineering tolerance for absolute signed "
            "RMST error, in percent of net RMST. Omit when no such tolerance was "
            "specified before analysis."
        ),
    )
    args = parser.parse_args()

    root = args.root.resolve()
    source = (args.replicates or root / "results" / "matr_primary" / "replicates.csv").resolve()
    out_dir = (args.out_dir or root / "results" / "revision_metrics").resolve()
    if not source.exists():
        raise FileNotFoundError(
            f"Missing {source}. Run matr_primary_analysis.py with R=200 first."
        )

    data = pd.read_csv(source)
    required = {
        "replicate", "beta", "scope", "arm", "truth_net_rmst", "signed_gap_pct"
    }
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"replicates.csv is missing columns: {sorted(missing)}")
    data = data[np.isclose(data["beta"].astype(float), 1.0)].copy()
    data = data[data["arm"].isin(["naive", "crossfit_tv_ipcw", "oracle_tv_ipcw"])].copy()

    overlay_rows: list[dict] = []
    summary_rows: list[dict] = []
    tex_lines = [
        "% Generated by code/revision_metrics.py. Do not edit.",
        r"\providecommand{\RevisionMetricsReady}{1}",
    ]

    for batch, (prefix, endpoint_status, bound_width) in BATCHES.items():
        batch_data = data[data["scope"] == batch]
        pivot = batch_data.pivot_table(
            index="replicate", columns="arm", values="signed_gap_pct", aggfunc="first"
        ).sort_index()
        required_arms = {"naive", "crossfit_tv_ipcw", "oracle_tv_ipcw"}
        if not required_arms.issubset(pivot.columns):
            raise ValueError(f"Missing required arms for {batch}: {required_arms - set(pivot.columns)}")
        truth_values = batch_data["truth_net_rmst"].dropna().astype(float).unique()
        if len(truth_values) != 1:
            raise ValueError(f"Expected one truth value for {batch}; got {truth_values}")
        truth = float(truth_values[0])

        for replicate, row in pivot.iterrows():
            naive = float(row["naive"])
            fitted = float(row["crossfit_tv_ipcw"])
            oracle = float(row["oracle_tv_ipcw"])
            abs_improvement = abs(naive) - abs(fitted)
            relative = (
                1.0 - abs(fitted) / abs(naive) if abs(naive) > 1e-12 else float("nan")
            )
            overlay_rows.append({
                "scope": batch,
                "batch_display": prefix,
                "replicate": int(replicate),
                "truth_net_rmst_cycles": truth,
                "naive_signed_error_pct": naive,
                "crossfit_signed_error_pct": fitted,
                "oracle_signed_error_pct": oracle,
                "crossfit_minus_naive_movement_pp": fitted - naive,
                "absolute_error_improvement_pp": abs_improvement,
                "relative_absolute_error_reduction": relative,
                "naive_absolute_error_pct": abs(naive),
                "crossfit_absolute_error_pct": abs(fitted),
            })

        o = pd.DataFrame([r for r in overlay_rows if r["scope"] == batch])
        mean_naive = float(o["naive_signed_error_pct"].mean())
        mean_fitted = float(o["crossfit_signed_error_pct"].mean())
        mean_oracle = float(o["oracle_signed_error_pct"].mean())
        mean_abs_naive = float(o["naive_absolute_error_pct"].mean())
        mean_abs_fitted = float(o["crossfit_absolute_error_pct"].mean())
        mean_abs_improvement = float(o["absolute_error_improvement_pp"].mean())
        relative_reduction = (
            1.0 - mean_abs_fitted / mean_abs_naive if mean_abs_naive > 1e-12 else float("nan")
        )
        movement = float(o["crossfit_minus_naive_movement_pp"].mean())
        movement_mcse = _mcse(o["crossfit_minus_naive_movement_pp"])
        improvement_mcse = _mcse(o["absolute_error_improvement_pp"])
        fitted_error_mcse = _mcse(o["crossfit_signed_error_pct"])
        adequacy = "not assessed (no external tolerance supplied)"
        if args.tolerance_pct is not None:
            adequacy = (
                "within tolerance" if abs(mean_fitted) <= float(args.tolerance_pct)
                else "outside tolerance"
            )

        summary_rows.append({
            "scope": batch,
            "batch_display": prefix,
            "endpoint_status": endpoint_status,
            "endpoint_identification_bound_width_cycles": bound_width,
            "R": int(len(o)),
            "truth_net_rmst_cycles": truth,
            "mean_naive_signed_error_pct": mean_naive,
            "mean_crossfit_signed_error_pct": mean_fitted,
            "mcse_crossfit_signed_error_pct": fitted_error_mcse,
            "mean_oracle_signed_error_pct": mean_oracle,
            "mean_naive_absolute_error_pct": mean_abs_naive,
            "mean_crossfit_absolute_error_pct": mean_abs_fitted,
            "mean_absolute_error_improvement_pp": mean_abs_improvement,
            "mcse_absolute_error_improvement_pp": improvement_mcse,
            "relative_absolute_error_reduction": relative_reduction,
            "mean_crossfit_minus_naive_movement_pp": movement,
            "mcse_crossfit_minus_naive_movement_pp": movement_mcse,
            "mean_crossfit_minus_naive_movement_cycles": movement * truth / 100.0,
            "mcse_crossfit_minus_naive_movement_cycles": movement_mcse * truth / 100.0,
            "engineering_tolerance_pct": args.tolerance_pct,
            "practical_adequacy": adequacy,
        })

        tex_lines.extend([
            rf"\providecommand{{\Matr{prefix}MoveMCSE}}{{{_fmt(movement_mcse)}}}",
            rf"\providecommand{{\Matr{prefix}MoveMCSECycles}}{{{_fmt(abs(movement_mcse * truth / 100.0), 2)}}}",
            rf"\providecommand{{\Matr{prefix}MeanAbsNaive}}{{{_fmt(mean_abs_naive)}}}",
            rf"\providecommand{{\Matr{prefix}MeanAbsCross}}{{{_fmt(mean_abs_fitted)}}}",
            rf"\providecommand{{\Matr{prefix}AbsImprove}}{{{_fmt(mean_abs_improvement)}}}",
            rf"\providecommand{{\Matr{prefix}AbsImproveMCSE}}{{{_fmt(improvement_mcse)}}}",
            rf"\providecommand{{\Matr{prefix}RelativeErrorReduction}}{{{_fmt(100.0 * relative_reduction, 1)}}}",
            rf"\providecommand{{\Matr{prefix}EndpointBoundWidth}}{{{_fmt(bound_width, 2)}}}",
        ])

    _write_csv(out_dir / "revision_accuracy_overlays.csv", overlay_rows)
    _write_csv(out_dir / "revision_accuracy_summary.csv", summary_rows)
    (out_dir / "revision_metrics.tex").write_text("\n".join(tex_lines) + "\n", encoding="utf-8")
    print(out_dir / "revision_accuracy_summary.csv")
    print(out_dir / "revision_accuracy_overlays.csv")
    print(out_dir / "revision_metrics.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
